# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('passport', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('diagnosis', models.TextField()),
            ],
        ),
    ]
